apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp-deployment
  labels:
    app: flaskapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp 
    spec:
      containers:
      - name: nodeserver
        image: ahmednageh08/flask-app:1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      #imagePullSecrets:
      #- name: regcred       
---

apiVersion: v1
kind: Service
metadata:
  name: flaskapp-service
spec:
  selector:
    app: flaskapp 
  type: ClusterIP
  ports:
  - port: 5000
    targetPort: 5000